# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

puts "🌱 Seeding spices..."

cars = [
    {
        "model": "Audi SQ5",
        "brand": "Audi",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-14_at_17.24.53.jpeg",
        "description": "The Audi SQ5 offers a unique combination of performance, luxury, and style. ",
        "price": "KES 7,600,000",
        "year_of_manufacture": 2020,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "6500KM",
        "engine_size": "3000CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Audi A7 Sportback",
        "brand": "Audi",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-22_at_09.53.05.jpeg",
        "description": "The Audi A7 Quattro is an all wheel drive with extensive features for a perfect drive and comfort.",
        "price": "KES 5,900,000",
        "year_of_manufacture": 2021,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "2500KM",
        "engine_size": "2500CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Audi A7 Quattro S-Line",
        "brand": "Audi",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-22_at_09.50.55.jpeg",
        "description": "A form of coupe version that offers comfort and a great road performance.",
        "price": "KES 5,750,000",
        "year_of_manufacture": 2020,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "15000KM",
        "engine_size": "2000CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Audi Q7",
        "brand": "Audi",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/ee4d11fc944342dabb71525a2dc7a2c3.jpg",
        "description": "Audi Q7 is a luxurious SUV that offers a spacious interior, a comfortable ride and a strong performance.",
        "price": "KES 8,900,000",
        "year_of_manufacture": 2019,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "21000KM",
        "engine_size": "3000CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Audi A6",
        "brand": "Audi",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-15_at_16.51.01.jpeg",
        "description": "The Audi A6 provides a V6 engine that gives a drive and ability to stretch to the maximum of its potential.",
        "price": "KES 3,900,000",
        "year_of_manufacture": 2020,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "15000KM",
        "engine_size": "2500CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Audi A5",
        "brand": "Audi",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-15_at_18.58.29.jpeg",
        "description": "The Audi A5 is designed to steal the attention wherever she goes but it doesn’t stop there.",
        "price": "KES 3,500,000",
        "year_of_manufacture": 2018,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "9500KM",
        "engine_size": "2000CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "BMW X6 XDrive30D",
        "brand": "BMW",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-12_at_14.36.24.jpeg",
        "description": "The BMW X6 M Sport offers an unbeatable combination of sporty performance and luxury features.",
        "price": "KES 9,500,000",
        "year_of_manufacture": 2020,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "4WD",
        "mileage": "18500KM",
        "engine_size": "3000CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "BMW X5 XDrive40D M Sport",
        "brand": "BMW",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-14_at_10.24.24_1.jpeg",
        "description": "The BMW XDrive40d M Sport is an all wheel drive perfect for urban drive and comfort.",
        "price": "KES 7,850,000",
        "year_of_manufacture": 2021,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "4WD",
        "mileage": "14500KM",
        "engine_size": "3000CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "BMW M4",
        "brand": "BMW",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/B5800F63-FAD6-455E-8694-8A74652E5584.jpeg",
        "description": "This sexy machine is 2021 unit with extremely low mileage and factory warranty✅",
        "price": "KES 15,650,000",
        "year_of_manufacture": "2021",
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "6778KM",
        "engine_size": "3000CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Mercedes GLE350D",
        "brand": "Mercedes Benz",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-24_at_13.47.44_1.jpeg",
        "description": "AMG Sports Package, Cream Leather interior, Panoramic Roof, Rear Entertainment.",
        "price": "KES 9,540,000",
        "year_of_manufacture": 2021,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "4WD",
        "mileage": "21000KM",
        "engine_size": "3000CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Mercedes Benz Maybach S Class",
        "brand": "Mercedes Benz",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-25_at_13.46.49_2.jpeg",
        "description": "First class cabin package,command online system with media interface,wireless charging.",
        "price": "KES 25,500,000",
        "year_of_manufacture": 2021,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "5500KM",
        "engine_size": "6000CC",
        "fuel": "Petrol",
        "transmission": "AWD"
    },
    {
        "model": "Mercedes GLS63H AMG Night edition",
        "brand": "Mercedes Benz",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/CC4BC6BA-ED40-4F70-AE28-77F008028818.jpeg",
        "description": "Carbon fibre trim & interior, Head up display, thermotronic climate control, warmth & comfort package",
        "price": "KES 35,500,000",
        "year_of_manufacture": 2023,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "4WD",
        "mileage": "150KM",
        "engine_size": "4000CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Mercedes E300 Coupe",
        "brand": "Mercedes Benz",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/6F751C2F-60B3-4769-A564-7EEF55805E9A.jpeg",
        "description": "Selenite gray with black leather & alcantara interior. The E300 coupe is quite rare on kenyan roads.",
        "price": "KES 6,800,000",
        "year_of_manufacture": 2020,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "2WD",
        "mileage": "22000KM",
        "engine_size": "3000CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Mercedes GLS63h V8 Biturbo AMG",
        "brand": "Mercedes Benz",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-21_at_14.01.14.jpeg",
        "description": "This model is preferebly a luxurious vehicle best for comfort and a perfect drive even for a family unit.",
        "price": "KES 28,750,000",
        "year_of_manufacture": 2022,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "3500KM",
        "engine_size": "4000CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Mercedes Benz AMG G63",
        "brand": "Mercedes Benz",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-13_at_10.12.14.jpeg",
        "description": "The world class mercedes G63 is an epitome of beauty, power, luxury and performance.",
        "price": "KES 45,000,000",
        "year_of_manufacture": 2020,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "15500KM",
        "engine_size": "4000CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Mercedes GLE 350d",
        "brand": "Mercedes Benz",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-12_at_15.12.35_10.jpeg",
        "description": "The GLE is an all-wheeldrive powered by a 3 littre diesel turbo v6 engine. All luxury, comfort and a perfect drive.",
        "price": "KES 22,500,000",
        "year_of_manufacture": 2020,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "25500KM",
        "engine_size": "3000CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Mazda CX5",
        "brand": "Mazda",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-04_at_19.33.31.jpeg",
        "description": "The 2020 Mazda CX-5 is an excellent choice for a reliable, practical, and stylish crossover SUV.",
        "price": "KES 45,000,000",
        "year_of_manufacture": 2020,
        "source_country": "Japan🇯🇵",
        "availability": "Available",
        "drive": "4WD",
        "mileage": "32500KM",
        "engine_size": "2200CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Toyota Hilux Double Cab GR Sport Facelift",
        "brand": "Toyota",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-27_at_09.01.21.jpeg",
        "description": "Front grille,LED fog lamps,black leather seats with red stitching,7-inch touchscreen infotainment.",
        "price": "KES 8,500,000",
        "year_of_manufacture": 2021,
        "source_country": "Japan🇯🇵",
        "availability": "Available",
        "drive": "4WD",
        "mileage": "35000KM",
        "engine_size": "2500CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Toyota Fortuner",
        "brand": "Toyota",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-21_at_11.29.05.jpeg",
        "description": "Even with a three-row seating arrangement the Toyota Fortuner doesn't feel cramped in any manner.",
        "price": "KES 8,500,000",
        "year_of_manufacture": 2020,
        "source_country": "Japan🇯🇵",
        "availability": "Available",
        "drive": "4WD",
        "mileage": "22500KM",
        "engine_size": "2800CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Toyota RAV4",
        "brand": "Toyota",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-16_at_17.28.53_1.jpeg",
        "description": "Toyota RAV4 is a popular compact SUV known for its reliability, versatility and practicality.",
        "price": "KES 6,450,000",
        "year_of_manufacture": 2021,
        "source_country": "Japan🇯🇵",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "18000KM",
        "engine_size": "2500CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Toyota Prado TZG",
        "brand": "Toyota",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-10_at_18.21.03_1.jpeg",
        "description": "The Toyota Prado TZG is a well-made, reliable vehicle that offers a lot of features and value for the money.",
        "price": "KES 9,500,000",
        "year_of_manufacture": 2020,
        "source_country": "Japan🇯🇵",
        "availability": "Available",
        "drive": "4WD",
        "mileage": "20000KM",
        "engine_size": "3000CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Lexus LX600",
        "brand": "Lexus",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-18_at_12.30.49.jpeg",
        "description": "Lexus has always been a status symbol for ages the world over. The Lexus LX600 is a testament to this.",
        "price": "KES 30,500,000",
        "year_of_manufacture": 2022,
        "source_country": "Japan🇯🇵",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "1000KM",
        "engine_size": "3500CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "LX 600",
        "brand": "Lexus",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-17_at_13.24.30.jpeg",
        "description": "LX 600 is one of the most prestigious vehicles with its ability to be aggressive on the bad lands",
        "price": "KES 35,500,000",
        "year_of_manufacture": 2022,
        "source_country": "Japan🇯🇵",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "500KM",
        "engine_size": "3500CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Lexus 450D",
        "brand": "Lexus",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-13_at_13.13.29.jpeg",
        "description": "The Lexus 450D fits a perfect driving experience in all aspects including utmost comfort",
        "price": "KES 15,500,000",
        "year_of_manufacture": 2019,
        "source_country": "South Africa🇿🇦",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "25000KM",
        "engine_size": "4500CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Volkswagen Toureg R-Line",
        "brand": "Volkswagen",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-10_at_10.13.34.jpeg",
        "description": "The Volkswagen Toureg is a great vehicle for those who need a reliable, comfortable, and powerful SUV.",
        "price": "KES 7,500,000",
        "year_of_manufacture": 2019,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "35000KM",
        "engine_size": "3000CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Volkswagen Golf R",
        "brand": "Volkswagen",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/C94CD06D-425E-4833-8B7C-FB71B048144A.jpeg",
        "description": "Volkswagen's deadly EA888 third gen engine paired with a haldex awd and twinclutch drivetrain.",
        "price": "KES 4,500,000",
        "year_of_manufacture": 2017,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "25000KM",
        "engine_size": "2500CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Nissan GTR",
        "brand": "Nissan",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-10_at_10.16.50.jpeg",
        "description": "The Nissan GTR is one of the most popular sports cars in the world. It is known for its incredible performance.",
        "price": "KES 12,500,000",
        "year_of_manufacture": 2019,
        "source_country": "Japan🇯🇵",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "12000KM",
        "engine_size": "3800CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Range Rover Vogue SV P530",
        "brand": "Land Rover",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-27_at_14.21.41.jpeg",
        "description": "Black leather interior,23-inch alloy rims,rear entertainment,SV intrepid inserts and privacy glass.",
        "price": "KES 38,500,000",
        "year_of_manufacture": 2022,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "10KM",
        "engine_size": "4400CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Rolls Royce Cullinan 6.8 V12",
        "brand": "Rolls Royce",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-27_at_11.26.10.jpeg",
        "description": "Piano black interior veneer,ambient air package,seatbelts in slate,rear picnic table.",
        "price": "KES 55,500,000",
        "year_of_manufacture": 2022,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "5KM",
        "engine_size": "6800CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Rolls Royce Cullinan 6.8 V12 ONYX",
        "brand": "Rolls Royce",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-27_at_10.41.19.jpeg",
        "description": "ONYX full carbon fibre exterior bodykit,self levelling wheel centre,ONYX carbon roof.",
        "price": "KES 48,500,000",
        "year_of_manufacture": 2020,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "5000KM",
        "engine_size": "6800CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Range Rover Vogue HSE",
        "brand": "Land Rover",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-24_at_15.24.54.jpeg",
        "description": "Santorini black with cream leather interior,Powered gesture tailgate,digital LED headlights.",
        "price": "KES 40,500,000",
        "year_of_manufacture": 2022,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "5500KM",
        "engine_size": "3000CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Volvo XC90 T5 4WD",
        "brand": "Volvo",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-25_at_17.26.25.jpeg",
        "description": "Beige interior,panoramic sunroof,9-inch touchscreen infotainmentsystem.",
        "price": "KES 7,500,000",
        "year_of_manufacture": 2019,
        "source_country": "Japan🇯🇵",
        "availability": "Available",
        "drive": "4WD",
        "mileage": "25000KM",
        "engine_size": "2500CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "Volvo XC90 T6 AWD R-Design",
        "brand": "Volvo",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-25_at_16.38.45.jpeg",
        "description": "Four zone automatic climate control,city safety automatic emergency braking.",
        "price": "KES 6,500,000",
        "year_of_manufacture": 2018,
        "source_country": "Japan🇯🇵",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "30000KM",
        "engine_size": "2500CC",
        "fuel": "Petrol",
        "transmission": "Automatic"
    },
    {
        "model": "LandRover Discovery V HSE",
        "brand": "Land Rover",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-24_at_18.08.12_1.jpeg",
        "description": "The indicated CIF price for auction vehicles is an estimate based on previous auction data.",
        "price": "KES 8,500,000",
        "year_of_manufacture": 2020,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "35000KM",
        "engine_size": "3000CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Range Rover Vogue",
        "brand": "Land Rover",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-24_at_13.35.47.jpeg",
        "description": "Bronze with perlino leather super low mileage, panorama sunroof, pixel LEDS , Fixed side steps.",
        "price": "KES 35,000,000",
        "year_of_manufacture": 2022,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "6000KM",
        "engine_size": "3000CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    },
    {
        "model": "Porsche Cayenne Plutinum TDV6",
        "brand": "Porsche",
        "image": "https://dashboard.kaiandkaro.com/media/vehicles/images/WhatsApp_Image_2023-03-20_at_17.02.57_1.jpeg",
        "description": "The Porsche Cayenne Plutinum has a 3 litre diesel engine that combines a package of performance.",
        "price": "KES 8,000,000",
        "year_of_manufacture": 2018,
        "source_country": "United Kingdom🇬🇧",
        "availability": "Available",
        "drive": "AWD",
        "mileage": "20000KM",
        "engine_size": "3000CC",
        "fuel": "Diesel",
        "transmission": "Automatic"
    }

]

cars.each{|car| Car.create(car)}

user1 = User.create(email: "test1@email.com", name: "testuser1", password: "abcuser1", phone: "123456001")
user2 = User.create(email: "test2@email.com", name: "testuser2", password: "abcuser2", phone: "123456002")
user3 = User.create(email: "test3@email.com", name: "testuser3", password: "abcuser3", phone: "123456003")
user4 = User.create(email: "test4@email.com", name: "testuser4", password: "abcuser4", phone: "123456004")
user5 = User.create(email: "test5@email.com", name: "testuser5", password: "abcuser5", phone: "123456005")

puts "✅ Done seeding!"